### ISSUE TITLE
http redirecting to https

### ISSUE THREAD

**Issue by tony** [erroneousboat/docker-django#9] opened 2016-05-06 17:21 UTC
e14ff89  http://localhost:9080/ redirects to https://localhost:9080/

Ubuntu 16.04

```
~/study/docker/docker-django/services/webserver/config master
❯ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

~/study/docker/docker-django/services/webserver/config master
❯ docker-compose --version
docker-compose version 1.7.1, build 6c29830
```

**Comment by jpbruinsslot** [comment] 2016-05-06 18:53
This is as intended, I'll update the readme to reflect this. Furthermore you can see configuration in nginx that does this: https://github.com/erroneousboat/docker-django/blob/master/services/webserver/config/nginx.tmpl#L23

**Comment by jpbruinsslot** [comment] 2016-05-06 18:56
Fixed in: https://github.com/erroneousboat/docker-django/commit/291ac86a5a0e40e69f2c41a19d2ea7237b71c2fa

**Closed as completed by jpbruinsslot** 2016-05-06 18:56 UTC

**Comment by tony** [comment] 2016-05-06 19:50
```
It worked!
Congratulations on your first Django-powered page.
```

Using the port 9443 works as expected

thank you @erroneousboat
